# Sourced by the live telemetry scripts (plan O7). The backends publish NO host port (OBS-SEC-1), so by default every
# backend call runs `curl` INSIDE the grafana container, which sits on polaris-net and resolves prometheus, loki, tempo,
# alertmanager, mailpit and otel-collector by name. The default URLs below are those internal addresses.
#   TELEMETRY_ACCESS=host  use host curl against the loopback ports of docker-compose.dev-ports.yml (make up-dev-ports)
# Individual PROM / LOKI / TEMPO / AM / MAILPIT / OTLP / GRAFANA env overrides still win.
# Provides: icurl (curl with the same args; no host files: pass bodies on stdin with icurl_in, read output from stdout).
if [ "${TELEMETRY_ACCESS:-network}" = host ]; then
  : "${PROM:=http://127.0.0.1:9090}" "${LOKI:=http://127.0.0.1:3100}" "${TEMPO:=http://127.0.0.1:3200}"
  : "${GRAFANA:=http://127.0.0.1:3000}"
  : "${AM:=http://127.0.0.1:9093}" "${MAILPIT:=http://127.0.0.1:8025}" "${OTLP:=http://127.0.0.1:4318}"
  icurl() { curl "$@"; }
  icurl_in() { curl "$@"; }
else
  : "${PROM:=http://prometheus:9090}" "${LOKI:=http://loki:3100}" "${TEMPO:=http://tempo:3200}"
  : "${GRAFANA:=http://grafana:3000}"
  : "${AM:=http://alertmanager:9093}" "${MAILPIT:=http://mailpit:8025}" "${OTLP:=http://otel-collector:4318}"
  icurl() { docker exec -i grafana curl "$@" </dev/null; }
  icurl_in() { docker exec -i grafana curl "$@"; }
fi
# Grafana admin credentials come from .env (generated by scripts/init-env.sh), never from the repo (plan O7).
envval() { grep -E "^$1=" .env 2>/dev/null | tail -1 | cut -d= -f2-; }
: "${GRAFANA_ADMIN_USER:=$(envval GRAFANA_ADMIN_USER)}"; : "${GRAFANA_ADMIN_USER:=admin}"
: "${GRAFANA_AUTH:=$GRAFANA_ADMIN_USER:${GRAFANA_ADMIN_PASSWORD:-$(envval GRAFANA_ADMIN_PASSWORD)}}"
export PROM LOKI TEMPO AM MAILPIT OTLP GRAFANA GRAFANA_AUTH
