// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using efcoreddd.Infra.Data;

#nullable disable

namespace efcoreddd.Infra.Migrations
{
    [DbContext(typeof(ContractDbContext))]
    partial class ContractDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("efcoreddd.Domain.Contract.ContractAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateInitiated")
                        .HasColumnType("date");

                    b.Property<Guid>("FinalVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fullfilled")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("efcoreddd.Domain.Contract.ContractVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AcceptanceDeadline")
                        .HasColumnType("date");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ContractAggregateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateSentToAuthors")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificationDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModificationReason")
                        .HasColumnType("integer");

                    b.Property<string>("WorkingTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("_hasRevisedSpecSet")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ContractAggregateId");

                    b.ToTable("ContractVersion");
                });

            modelBuilder.Entity("efcoreddd.Domain.Contract.ContractVersion", b =>
                {
                    b.HasOne("efcoreddd.Domain.Contract.ContractAggregate", null)
                        .WithMany("Versions")
                        .HasForeignKey("ContractAggregateId");

                    b.OwnsMany("efcoreddd.Domain.Contract.ValueObjects.Author", "Authors", b1 =>
                        {
                            b1.Property<Guid>("ContractVersionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Signed")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("SignedAuthorId")
                                .HasColumnType("uuid");

                            b1.HasKey("ContractVersionId", "__synthesizedOrdinal");

                            b1.ToTable("ContractVersion");

                            b1.ToJson("Authors");

                            b1.WithOwner()
                                .HasForeignKey("ContractVersionId");

                            b1.OwnsOne("efcoreddd.Domain.SharedKernel.ValueObjects.PersonName", "Name", b2 =>
                                {
                                    b2.Property<Guid>("AuthorContractVersionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Author__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("AuthorContractVersionId", "Author__synthesizedOrdinal");

                                    b2.ToTable("ContractVersion");

                                    b2.ToJson("Name");

                                    b2.WithOwner()
                                        .HasForeignKey("AuthorContractVersionId", "Author__synthesizedOrdinal");
                                });

                            b1.Navigation("Name")
                                .IsRequired();
                        });

                    b.OwnsOne("efcoreddd.Domain.Contract.ValueObjects.SpecificationSet", "Specs", b1 =>
                        {
                            b1.Property<Guid>("ContractVersionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AdvanceAmountUSD")
                                .HasColumnType("integer");

                            b1.Property<bool>("AuthorAvailableForPR")
                                .HasColumnType("boolean");

                            b1.Property<int>("DigitalRoyaltyPct")
                                .HasColumnType("integer");

                            b1.Property<int>("HardCoverRoyaltyPct")
                                .HasColumnType("integer");

                            b1.Property<decimal>("PriceForAddlAuthorCopiesUSD")
                                .HasColumnType("numeric");

                            b1.Property<int>("PromoCopiesForAuthor")
                                .HasColumnType("integer");

                            b1.Property<bool>("PublicityProvided")
                                .HasColumnType("boolean");

                            b1.Property<int>("SoftCoverRoyaltyPct")
                                .HasColumnType("integer");

                            b1.Property<int>("TranslationRoyaltyUSD")
                                .HasColumnType("integer");

                            b1.HasKey("ContractVersionId");

                            b1.ToTable("ContractVersion");

                            b1.ToJson("Specs");

                            b1.WithOwner()
                                .HasForeignKey("ContractVersionId");
                        });

                    b.Navigation("Authors");

                    b.Navigation("Specs")
                        .IsRequired();
                });

            modelBuilder.Entity("efcoreddd.Domain.Contract.ContractAggregate", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
