x-go_app_base: &app-base
  platform: ${PLATFORM}
  container_name: go_app
  build:
    context: ./src/go_app
    dockerfile: Dockerfile
services:
  app_migrate:
    image: postgres:16
    container_name: app_migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/net9app/Migrations/deploy:/scripts
    entrypoint: >
      bash -c "
        echo 'Waiting for database...' &&
        until pg_isready -h postgres -U admin; do sleep 1; done &&
        echo 'Running migration script...' &&
        psql -h postgres -U admin -d identity_db -f /scripts/openiddict.sql
      "
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
  app:
    container_name: dotnet8_app
    platform: ${PLATFORM}
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "6001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      GO_APP__ENDPOINT: "http://go_app:8080/"
      GO_APP__Timeout: "00:00:03"
    healthcheck:
      test: ["CMD", "busybox", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s
    depends_on:
      app_migrate:
        condition: service_completed_successfully
      otel-collector:
        condition: service_started
      go_app:
        condition: service_healthy
  go_app_migrate:
    <<: *app-base
    container_name: go_app_migrate
    entrypoint: ["/migrate"]
    volumes:
      - ./local/go_app_config.yml:/etc/go_app/config.yml
    deploy:
      replicas: 1
    depends_on:
      otel-collector:
        condition: service_started
      postgres:
        condition: service_healthy
  go_app:
    <<: *app-base
    container_name: go_app
    ports:
      - 6002:8080
    healthcheck:
      test: ["CMD", "busybox", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s
    volumes:
      - ./local/go_app_config.yml:/etc/go_app/config.yml
    depends_on:
      otel-collector:
        condition: service_started
      redis:
        condition: service_healthy
      go_app_migrate:
        condition: service_completed_successfully
  k6:
    image: grafana/k6
    container_name: k6
    deploy:
      replicas: 1
    environment:
      - APP_BaseUrl=http://app:8080
      - GO_APP_BaseUrl=http://go_app:8080
    volumes:
      - ./tests/k6:/k6
    entrypoint: ["sh", "/k6/run-all.sh"]
    depends_on:
      app:
        condition: service_healthy
  blackbox:
    # https://github.com/prometheus/blackbox_exporter/releases
    image: prom/blackbox-exporter:v0.26.0
    container_name: blackbox
    restart: unless-stopped
    ports:
      - 9115:9115
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./telemetry/blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    command: --config.file=/etc/blackbox/blackbox.yml
    depends_on:
      app:
        condition: service_healthy
      go_app:
        condition: service_healthy
    networks:
      - default
