services:
  app:
    container_name: dotnet8_app
    platform: linux/amd64
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "6001:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_SERVICE_NAME: "OTLP-Example"
    depends_on:
      - otel-collector
      - go_app
  go_app:
    platform: linux/amd64
    container_name: go_app
    build:
      context: ./src/go_app
      dockerfile: Dockerfile
    ports:
      - 6002:8080
    depends_on:
      - otel-collector
      - redis
  k6:
    image: grafana/k6
    container_name: k6
    environment:
      - APP_BaseUrl=http://app:5000
      - GO_APP_BaseUrl=http://go_app:8080
    volumes:
      - ./tests/k6:/k6
    entrypoint: ["sh", "/k6/run-all.sh"]
    depends_on:
      - app
  blackbox:
    # https://github.com/prometheus/blackbox_exporter/releases
    image: prom/blackbox-exporter:v0.26.0
    container_name: blackbox
    restart: unless-stopped
    ports:
      - 9115:9115
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./telemetry/blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    command: --config.file=/etc/blackbox/blackbox.yml
    networks:
      - default
