services:
  app:
    container_name: dotnet8_app
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_SERVICE_NAME: "OTLP-Example"
    depends_on:
      - otel-collector
  k6:
    image: grafana/k6
    container_name: k6
    environment:
      - APP_BaseUrl=http://app:5000
    volumes:
      - ./tests/k6:/k6
    entrypoint: ["sh", "/k6/run-all.sh"]
    depends_on:
      - app
