package vn.danang.polaris.assistant.model;

import java.util.Collections;
import java.util.List;

/**
 * Represents the response from an AI Foundation Model.
 * May contain textual completion and/or a list of requested tool calls.
 *
 * @param text the textual reply generated by the model
 * @param toolCalls any tool calls proposed by the model
 */
public record ModelResponse(
        String text,
        List<ToolCall> toolCalls
) {
    public ModelResponse(String text) {
        this(text, List.of());
    }

    @Override
    public List<ToolCall> toolCalls() {
        return toolCalls != null ? toolCalls : Collections.emptyList();
    }

    public boolean hasToolCalls() {
        return toolCalls != null && !toolCalls.isEmpty();
    }
}
