package vn.danang.polaris.assistant.model;

import java.util.Map;

/**
 * Represents a tool call requested by the AI Foundation Model.
 *
 * @param name the unique name of the tool to execute
 * @param arguments the arguments map to pass to the tool
 * @param thoughtSignature the opaque thought signature generated by the model for this call
 */
public record ToolCall(
        String name,
        Map<String, Object> arguments,
        String thoughtSignature
) {
    public ToolCall(String name, Map<String, Object> arguments) {
        this(name, arguments, null);
    }

    public ToolCall {
        if (arguments == null) {
            arguments = Map.of();
        }
    }
}
