"""
Script to generate the gemini_agent_calculator.ipynb Jupyter Notebook.
"""
import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🤖 Simple AI Agent with Calculator Tool Calling\n",
                "### Powered by Gemini 3.6 Flash (`gemini-3.6-flash`) and the Google GenAI SDK\n",
                "\n",
                "This notebook demonstrates how an **AI Agent** works under the hood using **Tool Use (Function Calling)**.\n",
                "\n",
                "### 🔍 Key Features of This Demonstration:\n",
                "1. **Full API Visibility**: Logs the exact request and response payloads on every single turn (model inputs, candidate outputs, function call arguments, and tool execution results).\n",
                "2. **Dual Logging Modes**:\n",
                "   - **Structured Payload Inspector**: Clean, formatted JSON showing conversation history, tool definitions, and token usage.\n",
                "   - **HTTP Wire-Level Logger**: Intercepts the raw HTTP POST requests and responses to `generativelanguage.googleapis.com` via `httpx` event hooks.\n",
                "3. **Transparent Agent Loop**: Step-by-step implementation of an agent loop that:\n",
                "   - Sends user messages and tool declarations to Gemini.\n",
                "   - Intercepts the model's decision to invoke a tool.\n",
                "   - Executes the calculator tool locally in Python.\n",
                "   - Returns the result back to Gemini in the next turn to synthesize the final answer.\n",
                "4. **Multiple Tool Calls in a Single Turn (Parallel Tooling)**: Demonstrates how Gemini 3.6 Flash emits multiple function calls simultaneously in one turn, and how the agent bundles all execution responses back in a single turn.\n",
                "5. **Multiple Scenarios**: Direct calculations, multi-step reasoning word problems, parallel geometry/orders, and non-math queries."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "--- \n",
                "## 1. Environment Setup and Installation\n",
                "\n",
                "Ensure you have the current `google-genai` Python SDK installed (version >= 2.0.0)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Check and install google-genai SDK if not already present\n",
                "import sys\n",
                "\n",
                "try:\n",
                "    import google.genai\n",
                "    print(f\"✅ google-genai is already installed: version {google.genai.__version__}\")\n",
                "    print(f\"Current Python executable: {sys.executable}\")\n",
                "except ImportError:\n",
                "    print(\"Installing google-genai...\")\n",
                "    %pip install -q -U --disable-pip-version-check google-genai\n",
                "    print(\"✅ Installation complete. If needed, please restart the kernel.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 🔑 Configure Your Gemini API Key\n",
                "\n",
                "You can get a Gemini API key for free from [Google AI Studio](https://aistudio.google.com/).\n",
                "The code below will check your environment variables or prompt you securely for the key."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import getpass\n",
                "\n",
                "# Check if GEMINI_API_KEY is already present\n",
                "if not os.environ.get(\"GEMINI_API_KEY\"):\n",
                "    key = getpass.getpass(\"Enter your Gemini API Key (or leave blank to enter in next cell): \").strip()\n",
                "    if key:\n",
                "        os.environ[\"GEMINI_API_KEY\"] = key\n",
                "        print(\"✅ GEMINI_API_KEY configured for this notebook session.\")\n",
                "    else:\n",
                "        print(\"ℹ️ No key entered yet. You can also get a free key from https://aistudio.google.com/\")\n",
                "else:\n",
                "    print(\"✅ GEMINI_API_KEY is already present in environment.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "--- \n",
                "## 2. Initialize the Gemini Client\n",
                "\n",
                "We use `google.genai.Client()`. The target model is **`gemini-3.6-flash`**.\n",
                "If the API key is not yet set, this cell will prompt you directly."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import getpass\n",
                "from google import genai\n",
                "from google.genai import types\n",
                "\n",
                "MODEL_ID = \"gemini-3.6-flash\"\n",
                "\n",
                "# Auto-prompt if key is not yet set\n",
                "api_key = os.environ.get(\"GEMINI_API_KEY\")\n",
                "if not api_key:\n",
                "    print(\"🔑 GEMINI_API_KEY not found in environment.\")\n",
                "    api_key = getpass.getpass(\"👉 Paste your Gemini API Key here (from https://aistudio.google.com/): \").strip()\n",
                "    if not api_key:\n",
                "        api_key = input(\"👉 Or type your key here: \").strip()\n",
                "    os.environ[\"GEMINI_API_KEY\"] = api_key\n",
                "\n",
                "client = genai.Client(api_key=api_key)\n",
                "print(f\"✅ Client successfully initialized! Target Model: {MODEL_ID}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "--- \n",
                "## 3. Define the Calculator Tools\n",
                "\n",
                "When creating tools for Gemini:\n",
                "- Python functions should include **type hints** for all arguments and return values.\n",
                "- Include a **docstring** explaining what the function does and what each parameter means.\n",
                "Gemini uses these docstrings and type annotations to generate the tool's JSON schema and decide when and how to call it."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import ast\n",
                "import operator\n",
                "import math\n",
                "from typing import Union, Dict, Any\n",
                "\n",
                "# --- Basic Arithmetic Tools ---\n",
                "\n",
                "def add(a: float, b: float) -> float:\n",
                "    \"\"\"Adds two numbers together.\n",
                "\n",
                "    Args:\n",
                "        a: The first number.\n",
                "        b: The second number.\n",
                "    \"\"\"\n",
                "    return float(a + b)\n",
                "\n",
                "def subtract(a: float, b: float) -> float:\n",
                "    \"\"\"Subtracts b from a (a - b).\n",
                "\n",
                "    Args:\n",
                "        a: The number to subtract from.\n",
                "        b: The number to subtract.\n",
                "    \"\"\"\n",
                "    return float(a - b)\n",
                "\n",
                "def multiply(a: float, b: float) -> float:\n",
                "    \"\"\"Multiplies two numbers together.\n",
                "\n",
                "    Args:\n",
                "        a: The first factor.\n",
                "        b: The second factor.\n",
                "    \"\"\"\n",
                "    return float(a * b)\n",
                "\n",
                "def divide(a: float, b: float) -> Union[float, str]:\n",
                "    \"\"\"Divides a by b (a / b).\n",
                "\n",
                "    Args:\n",
                "        a: The numerator.\n",
                "        b: The denominator.\n",
                "    \"\"\"\n",
                "    if b == 0:\n",
                "        return \"Error: Division by zero is undefined.\"\n",
                "    return float(a / b)\n",
                "\n",
                "def power(base: float, exponent: float) -> float:\n",
                "    \"\"\"Calculates base raised to the power of exponent (base ** exponent).\n",
                "\n",
                "    Args:\n",
                "        base: The base number.\n",
                "        exponent: The exponent power.\n",
                "    \"\"\"\n",
                "    return float(base ** exponent)\n",
                "\n",
                "# --- Geometry Tools (Ideal for Parallel Multi-Tool Invocations) ---\n",
                "\n",
                "def calculate_circle_area(radius: float) -> float:\n",
                "    \"\"\"Calculates the area of a circle given its radius in meters.\n",
                "\n",
                "    Args:\n",
                "        radius: The circle radius in meters.\n",
                "    \"\"\"\n",
                "    return round(float(math.pi * (radius ** 2)), 4)\n",
                "\n",
                "def calculate_hypotenuse(a: float, b: float) -> float:\n",
                "    \"\"\"Calculates the hypotenuse of a right triangle given legs a and b.\n",
                "\n",
                "    Args:\n",
                "        a: Length of side a.\n",
                "        b: Length of side b.\n",
                "    \"\"\"\n",
                "    return round(float(math.sqrt(a ** 2 + b ** 2)), 4)\n",
                "\n",
                "def calculate_cylinder_volume(radius: float, height: float) -> float:\n",
                "    \"\"\"Calculates the volume of a cylinder given radius and height.\n",
                "\n",
                "    Args:\n",
                "        radius: Circular base radius.\n",
                "        height: Cylinder height.\n",
                "    \"\"\"\n",
                "    return round(float(math.pi * (radius ** 2) * height), 4)\n",
                "\n",
                "def calculate_line_item_subtotal(item_name: str, quantity: int, unit_price: float) -> Dict[str, Any]:\n",
                "    \"\"\"Calculates the subtotal for an order line item.\n",
                "\n",
                "    Args:\n",
                "        item_name: Name of the product.\n",
                "        quantity: Quantity purchased.\n",
                "        unit_price: Price per unit in USD.\n",
                "    \"\"\"\n",
                "    subtotal = quantity * unit_price\n",
                "    return {\"item_name\": item_name, \"quantity\": quantity, \"unit_price\": unit_price, \"subtotal\": round(subtotal, 2)}\n",
                "\n",
                "# --- Advanced Math Expression Evaluator ---\n",
                "\n",
                "_SAFE_OPERATORS = {\n",
                "    ast.Add: operator.add,\n",
                "    ast.Sub: operator.sub,\n",
                "    ast.Mult: operator.mul,\n",
                "    ast.Div: operator.truediv,\n",
                "    ast.Pow: operator.pow,\n",
                "    ast.Mod: operator.mod,\n",
                "    ast.USub: operator.neg,\n",
                "    ast.UAdd: operator.pos,\n",
                "}\n",
                "\n",
                "def _eval_ast(node):\n",
                "    if isinstance(node, ast.Expression):\n",
                "        return _eval_ast(node.body)\n",
                "    elif isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):\n",
                "        return node.value\n",
                "    elif isinstance(node, ast.BinOp):\n",
                "        left = _eval_ast(node.left)\n",
                "        right = _eval_ast(node.right)\n",
                "        op_type = type(node.op)\n",
                "        if op_type in _SAFE_OPERATORS:\n",
                "            return _SAFE_OPERATORS[op_type](left, right)\n",
                "        raise ValueError(f\"Unsupported binary operator: {op_type.__name__}\")\n",
                "    elif isinstance(node, ast.UnaryOp):\n",
                "        operand = _eval_ast(node.operand)\n",
                "        op_type = type(node.op)\n",
                "        if op_type in _SAFE_OPERATORS:\n",
                "            return _SAFE_OPERATORS[op_type](operand)\n",
                "        raise ValueError(f\"Unsupported unary operator: {op_type.__name__}\")\n",
                "    else:\n",
                "        raise ValueError(f\"Unsupported syntax element: {type(node).__name__}\")\n",
                "\n",
                "def calculate_expression(expression: str) -> Union[float, str]:\n",
                "    \"\"\"Safely evaluates a full mathematical expression string.\n",
                "    Supports parentheses, +, -, *, /, **, and %.\n",
                "\n",
                "    Args:\n",
                "        expression: The mathematical expression, e.g. '(15 * 24) + (100 / 4)'.\n",
                "    \"\"\"\n",
                "    try:\n",
                "        clean_expr = expression.strip().replace(\"^\", \"**\")\n",
                "        parsed = ast.parse(clean_expr, mode=\"eval\")\n",
                "        return float(_eval_ast(parsed))\n",
                "    except Exception as e:\n",
                "        return f\"Error evaluating expression '{expression}': {str(e)}\"\n",
                "\n",
                "# Registry mapping function names to callable functions\n",
                "TOOL_REGISTRY = {\n",
                "    \"add\": add,\n",
                "    \"subtract\": subtract,\n",
                "    \"multiply\": multiply,\n",
                "    \"divide\": divide,\n",
                "    \"power\": power,\n",
                "    \"calculate_circle_area\": calculate_circle_area,\n",
                "    \"calculate_hypotenuse\": calculate_hypotenuse,\n",
                "    \"calculate_cylinder_volume\": calculate_cylinder_volume,\n",
                "    \"calculate_line_item_subtotal\": calculate_line_item_subtotal,\n",
                "    \"calculate_expression\": calculate_expression,\n",
                "}\n",
                "\n",
                "# List of tools to pass to Gemini\n",
                "TOOLS_LIST = list(TOOL_REGISTRY.values())\n",
                "\n",
                "print(f\"Registered {len(TOOL_REGISTRY)} calculator tools:\")\n",
                "for name in TOOL_REGISTRY:\n",
                "    print(f\"  - {name}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "--- \n",
                "## 4. Setting Up Request & Response Payloads Logging\n",
                "\n",
                "Here we build two inspection layers:\n",
                "1. **Structured Turn Logger**: Formats the exact conversation history, function call requests, tool execution returns, and Gemini usage tokens.\n",
                "2. **HTTP Wire Logger (Optional toggle)**: Hooks directly into `httpx` to log raw JSON requests and responses transmitted over the wire to `generativelanguage.googleapis.com`."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import json\n",
                "import httpx\n",
                "\n",
                "class PayloadLogger:\n",
                "    \"\"\"Helper to format and display API request/response payloads at each turn.\"\"\"\n",
                "\n",
                "    @staticmethod\n",
                "    def log_request(turn: int, contents: list, tools: list, model: str):\n",
                "        print(\"\\n\" + \"=\"*80)\n",
                "        print(f\"📤 [TURN {turn}] REQUEST PAYLOAD SENT TO GEMINI ({model})\")\n",
                "        print(\"=\"*80)\n",
                "        \n",
                "        # Serialize contents list\n",
                "        serialized_contents = []\n",
                "        for c in contents:\n",
                "            if hasattr(c, \"model_dump\"):\n",
                "                serialized_contents.append(c.model_dump(exclude_none=True))\n",
                "            else:\n",
                "                serialized_contents.append(str(c))\n",
                "        \n",
                "        payload_summary = {\n",
                "            \"model\": model,\n",
                "            \"available_tools\": [t.__name__ for t in tools],\n",
                "            \"conversation_history\": serialized_contents\n",
                "        }\n",
                "        print(json.dumps(payload_summary, indent=2, default=str))\n",
                "\n",
                "    @staticmethod\n",
                "    def log_response(turn: int, response):\n",
                "        print(\"\\n\" + \"=\"*80)\n",
                "        print(f\"📥 [TURN {turn}] RESPONSE PAYLOAD RECEIVED FROM GEMINI\")\n",
                "        print(\"=\"*80)\n",
                "        \n",
                "        # Dump full response object or clean summary\n",
                "        if hasattr(response, \"model_dump\"):\n",
                "            resp_dict = response.model_dump(exclude_none=True)\n",
                "        else:\n",
                "            resp_dict = str(response)\n",
                "            \n",
                "        print(json.dumps(resp_dict, indent=2, default=str))\n",
                "\n",
                "    @staticmethod\n",
                "    def log_tool_execution(tool_name: str, args: dict, result):\n",
                "        print(\"\\n\" + \"-\"*80)\n",
                "        print(f\"⚙️  [LOCAL TOOL EXECUTION] {tool_name}\")\n",
                "        print(f\"   Input Arguments: {json.dumps(args, default=str)}\")\n",
                "        print(f\"   Execution Output: {result}\")\n",
                "        print(\"-\"*80)\n",
                "\n",
                "\n",
                "# --- Optional HTTP Wire-Level Interceptor ---\n",
                "WIRE_LOGGING_ENABLED = False\n",
                "\n",
                "def http_wire_request_hook(request: httpx.Request):\n",
                "    if not WIRE_LOGGING_ENABLED:\n",
                "        return\n",
                "    print(f\"\\n🌐 [HTTP WIRE OUT] {request.method} {request.url}\")\n",
                "    if request.content:\n",
                "        try:\n",
                "            body = json.loads(request.content.decode(\"utf-8\"))\n",
                "            print(\"   Wire JSON Body:\", json.dumps(body, indent=2)[:500], \"... (truncated)\")\n",
                "        except Exception:\n",
                "            pass\n",
                "\n",
                "def http_wire_response_hook(response: httpx.Response):\n",
                "    if not WIRE_LOGGING_ENABLED:\n",
                "        return\n",
                "    print(f\"\\n🌐 [HTTP WIRE IN] Status: {response.status_code}\")\n",
                "\n",
                "# Attach to client httpx instance\n",
                "if hasattr(client, \"_api_client\") and hasattr(client._api_client, \"_httpx_client\"):\n",
                "    client._api_client._httpx_client.event_hooks[\"request\"].append(http_wire_request_hook)\n",
                "    client._api_client._httpx_client.event_hooks[\"response\"].append(http_wire_response_hook)\n",
                "    print(\"✅ HTTP Wire logging hooks registered (disabled by default, toggle WIRE_LOGGING_ENABLED = True to view).\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "--- \n",
                "## 5. The AI Agent Loop Implementation\n",
                "\n",
                "This function implements the core cycle of an autonomous AI Agent:\n",
                "```mermaid\n",
                "flowchart TD\n",
                "    A[User Prompt] --> B[Log Request Payload]\n",
                "    B --> C[Send to Gemini 3.6 Flash]\n",
                "    C --> D[Log Response Payload]\n",
                "    D --> E{Does response contain FunctionCall?}\n",
                "    E -- Yes --> F[Execute Calculator Tool in Python]\n",
                "    F --> G[Append Tool Result to History]\n",
                "    G --> B\n",
                "    E -- No --> H[Synthesized Final Answer]\n",
                "```\n",
                "\n",
                "By disabling SDK automatic calling (`automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True)`), **we retain full control over each turn**, logging the request and response before and after each execution."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def run_calculator_agent(user_prompt: str, model: str = MODEL_ID, max_turns: int = 5, verbose: bool = True) -> str:\n",
                "    \"\"\"Runs an AI Agent with calculator tools, logging request and response payloads on every turn.\"\"\"\n",
                "    print(\"\\n\" + \"#\"*80)\n",
                "    print(f\"🚀 STARTING AGENT TASK: \\\"{user_prompt}\\\"\")\n",
                "    print(\"#\"*80)\n",
                "    \n",
                "    # Initialize conversation history with user message\n",
                "    contents = [\n",
                "        types.Content(\n",
                "            role=\"user\",\n",
                "            parts=[types.Part.from_text(text=user_prompt)]\n",
                "        )\n",
                "    ]\n",
                "    \n",
                "    # Configure tools and disable automatic function calling so we control and log every turn\n",
                "    config = types.GenerateContentConfig(\n",
                "        tools=TOOLS_LIST,\n",
                "        temperature=0.0,  # Zero temperature for deterministic math reasoning\n",
                "        automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),\n",
                "        system_instruction=\"You are a precise mathematical assistant. Use the provided calculator tools whenever performing calculations rather than calculating mental arithmetic.\"\n",
                "    )\n",
                "    \n",
                "    turn = 1\n",
                "    while turn <= max_turns:\n",
                "        # 1. Log the exact outgoing request payload\n",
                "        if verbose:\n",
                "            PayloadLogger.log_request(turn=turn, contents=contents, tools=TOOLS_LIST, model=model)\n",
                "        \n",
                "        # 2. Call Gemini 3.6 Flash\n",
                "        response = client.models.generate_content(\n",
                "            model=model,\n",
                "            contents=contents,\n",
                "            config=config\n",
                "        )\n",
                "        \n",
                "        # 3. Log the exact incoming response payload\n",
                "        if verbose:\n",
                "            PayloadLogger.log_response(turn=turn, response=response)\n",
                "        \n",
                "        # Check if the model made one or more function calls\n",
                "        if not response.function_calls:\n",
                "            print(\"\\n\" + \"*\"*80)\n",
                "            print(f\"🎯 [AGENT FINAL ANSWER - COMPLETED IN {turn} TURN(S)]:\")\n",
                "            print(response.text)\n",
                "            print(\"*\"*80)\n",
                "            return response.text\n",
                "        \n",
                "        # Detect and highlight parallel tool calls\n",
                "        num_calls = len(response.function_calls)\n",
                "        if num_calls > 1:\n",
                "            print(\"\\n\" + \"⚡\"*40)\n",
                "            print(f\"⚡ [PARALLEL TOOL CALLS DETECTED]: Gemini emitted {num_calls} tool calls in Turn {turn}!\")\n",
                "            for idx, fc in enumerate(response.function_calls, 1):\n",
                "                print(f\"   [{idx}] {fc.name}({fc.args})\")\n",
                "            print(\"⚡\"*40)\n",
                "        \n",
                "        # Append the model's response (which contains function_call) to history\n",
                "        model_content = response.candidates[0].content\n",
                "        contents.append(model_content)\n",
                "        \n",
                "        # 4. Execute the requested tool(s) locally\n",
                "        print(f\"\\n⚙️  [EXECUTING {num_calls} TOOL CALL(S) LOCALLY]\")\n",
                "        tool_response_parts = []\n",
                "        for fc in response.function_calls:\n",
                "            tool_name = fc.name\n",
                "            tool_args = fc.args or {}\n",
                "            \n",
                "            if tool_name not in TOOL_REGISTRY:\n",
                "                result = f\"Error: Tool '{tool_name}' not found.\"\n",
                "            else:\n",
                "                try:\n",
                "                    func = TOOL_REGISTRY[tool_name]\n",
                "                    result = func(**tool_args)\n",
                "                except Exception as err:\n",
                "                    result = f\"Error executing {tool_name}: {str(err)}\"\n",
                "            \n",
                "            PayloadLogger.log_tool_execution(tool_name, tool_args, result)\n",
                "            \n",
                "            # Create function_response part for Gemini\n",
                "            tool_response_parts.append(\n",
                "                types.Part.from_function_response(\n",
                "                    name=tool_name,\n",
                "                    response={\"result\": result}\n",
                "                )\n",
                "            )\n",
                "            \n",
                "        # 5. Append tool results as user turn to conversation history\n",
                "        contents.append(\n",
                "            types.Content(\n",
                "                role=\"user\",\n",
                "                parts=tool_response_parts\n",
                "            )\n",
                "        )\n",
                "        \n",
                "        turn += 1\n",
                "    \n",
                "    print(\"⚠️ Max turns reached without final answer.\")\n",
                "    return \"Max turns reached.\""
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "--- \n",
                "## 6. Demonstration Scenarios\n",
                "\n",
                "### Scenario 1: Direct Single Calculation\n",
                "Let's test an arithmetic question where Gemini needs to call a tool: `What is 4829 multiplied by 713?`"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "prompt1 = \"What is 4829 multiplied by 713?\"\n",
                "answer1 = run_calculator_agent(prompt1)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Scenario 2: Multi-Step Word Problem\n",
                "Let's test a real-world multi-step reasoning problem:\n",
                "\n",
                "> *\"A warehouse has 35 crates of apples. Each crate contains 120 apples. If 5 crates are spoiled and thrown away, and the remaining apples are distributed equally among 6 local grocery stores, how many apples does each store get?\"*\n",
                "\n",
                "Watch how Gemini decomposes the problem and either calls `calculate_expression` or invokes multiple arithmetic tools step-by-step!"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "prompt2 = (\n",
                "    \"A warehouse has 35 crates of apples. Each crate contains 120 apples. \"\n",
                "    \"If 5 crates are spoiled and thrown away, and the remaining apples are distributed \"\n",
                "    \"equally among 6 local grocery stores, how many apples does each store get?\"\n",
                ")\n",
                "answer2 = run_calculator_agent(prompt2)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Scenario 3: Complex Nested Expression & Powers\n",
                "Let's test an expression involving powers and division: `Calculate: (2 ** 12) + (5400 / 18) - (45 * 13)`"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "prompt3 = \"Please calculate: (2 ** 12) + (5400 / 18) - (45 * 13)\"\n",
                "answer3 = run_calculator_agent(prompt3)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Scenario 4: Non-Math Question (Tool Avoidance Check)\n",
                "An intelligent agent must only call tools when relevant. If asked a conceptual question, Gemini should respond directly without invoking the calculator."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "prompt4 = \"Explain what an autonomous AI Agent is in 2 concise sentences.\"\n",
                "answer4 = run_calculator_agent(prompt4)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Scenario 5: Multiple (Parallel) Tool Calls in a Single Turn\n",
                "\n",
                "When a prompt asks for multiple independent operations, **Gemini 3.6 Flash emits multiple `FunctionCall` parts in a single response turn**:\n",
                "\n",
                "1. **Turn 1 (Response)**: Gemini emits 3 parallel function calls simultaneously (`calculate_circle_area`, `calculate_hypotenuse`, `calculate_cylinder_volume`).\n",
                "2. **Local Execution**: The agent executes all 3 tools in Python.\n",
                "3. **Turn 2 (Request)**: The agent packages all 3 `function_response` parts into **a single user turn** and sends them back to Gemini.\n",
                "4. **Turn 2 (Response)**: Gemini synthesizes the final comparative answer in one shot!"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "prompt5 = (\n",
                "    \"Compute the following measurements in parallel:\\n\"\n",
                "    \"1. Area of a circle with radius 7 meters\\n\"\n",
                "    \"2. Hypotenuse of a right triangle with sides 9 and 12 meters\\n\"\n",
                "    \"3. Volume of a cylinder with radius 4 meters and height 15 meters\"\n",
                ")\n",
                "answer5 = run_calculator_agent(prompt5)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Scenario 6: Parallel Financial Subtotals & Total Order Calculation\n",
                "\n",
                "In order and invoice processing, multiple line items can be calculated in parallel before computing the grand total."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "prompt6 = (\n",
                "    \"Calculate the subtotal for each of these three items in parallel:\\n\"\n",
                "    \"1. 14 Laptops at $899.50 each\\n\"\n",
                "    \"2. 30 Monitors at $249.00 each\\n\"\n",
                "    \"3. 25 Keyboards at $49.99 each\\n\"\n",
                "    \"Then calculate the grand total for the whole order.\"\n",
                ")\n",
                "answer6 = run_calculator_agent(prompt6)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "--- \n",
                "## 7. Comparison: SDK Automatic Function Calling Mode\n",
                "\n",
                "In standard application development where manual logging of every step isn't needed, `google-genai` supports **automatic function calling** out of the box.\n",
                "\n",
                "The SDK will automatically:\n",
                "1. Detect the tool call\n",
                "2. Execute the local Python function\n",
                "3. Send the `function_response` back to Gemini\n",
                "4. Return the final synthesized response directly!"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Automatic function calling example (default SDK behavior)\n",
                "auto_config = types.GenerateContentConfig(\n",
                "    tools=TOOLS_LIST,\n",
                "    temperature=0.0,\n",
                ")\n",
                "\n",
                "auto_response = client.models.generate_content(\n",
                "    model=MODEL_ID,\n",
                "    contents=\"Calculate (999 * 888) / 3\",\n",
                "    config=auto_config\n",
                ")\n",
                "\n",
                "print(\"Result with Automatic Function Calling:\")\n",
                "print(auto_response.text)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "--- \n",
                "## 8. Summary & Key Takeaways\n",
                "\n",
                "1. **Gemini 3.6 Flash (`gemini-3.6-flash`)** is fast, cost-effective, and highly reliable at identifying tool triggers and formatting valid arguments.\n",
                "2. **Function Calling Architecture**:\n",
                "   - **Model side**: Chooses the tool and formats parameters into a `function_call` structure.\n",
                "   - **Client/Agent side**: Executes the function securely in the host environment (API calls, math, database queries, etc.).\n",
                "   - **Synthesis turn**: Client sends `function_response` back to Gemini, and Gemini produces human-readable output incorporating the tool's return value.\n",
                "3. **Observability**: Logging raw request payloads (`contents`, `role`, `parts`) and response payloads (`candidates`, `function_calls`, `usage_metadata`) is critical for debugging agent reasoning, verifying tool arguments, and tracking token costs."
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (.venv)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.14.6"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open("/Users/vung.do/projects/hometask1/src/gemini/agent-sample-1/gemini_agent_calculator.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("✅ Successfully generated gemini_agent_calculator.ipynb")
