datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  url: http://prometheus:9090
  jsonData:
    timeInterval: 10s
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
- name: Loki
  access: proxy
  type: loki
  url: http://loki:3100
  isDefault: true
- name: Tempo
  access: proxy
  type: tempo
  url: http://tempo:3200
  isDefault: true
- name: InfluxDB
  access: proxy
  type: influxdb
  url: http://influxdb:8086
  database: k6
  isDefault: true
