global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: local-stack
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'otel-collector:2113'
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://host.docker.internal:6001/health #Weather App API
        - http://host.docker.internal:6002/health #Weather App API
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115